version: '3.0'
services:
  device-agent:
    container_name: macchina-device-agent
    image: "macchina/device-agent"
    restart: always
    environment:
      WEBTUNNEL_DOMAIN: ${WEBTUNNEL_DOMAIN:?domain is required}
      WEBTUNNEL_DEVICE_ID: ${WEBTUNNEL_DEVICE_ID:?device ID is required}
      WEBTUNNEL_DEVICE_NAME: ${WEBTUNNEL_DEVICE_NAME:-Unnamed Device}
      WEBTUNNEL_HOST: ${WEBTUNNEL_HOST:-172.17.0.1}
      WEBTUNNEL_HTTP_PORT: ${WEBTUNNEL_HTTP_PORT:-0}
      WEBTUNNEL_HTTPS_ENABLE: ${WEBTUNNEL_HTTPS_ENABLE:-false}
      WEBTUNNEL_SSH_PORT: ${WEBTUNNEL_SSH_PORT:-0}
      WEBTUNNEL_VNC_PORT: ${WEBTUNNEL_VNC_PORT:-0}
      WEBTUNNEL_RDP_PORT: ${WEBTUNNEL_RDP_PORT:-0}
      WEBTUNNEL_EXTRA_PORTS: ${WEBTUNNEL_EXTRA_PORTS:-}
      WEBTUNNEL_REFLECTOR_URI: ${WEBTUNNEL_REFLECTOR_URI:-https://remote.macchina.io}
