name: meta-agent-docker-ci
on: [push, workflow_dispatch]
jobs:
  docker-build-amd64:
    runs-on: ubuntu-20.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to hub.docker.com
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build Docker Image
        run: |
          VERSION=`./version.sh`
          echo Version: ${VERSION}
          docker build . -t macchina/device-agent:latest-amd64 -t macchina/device-agent:${VERSION}-amd64
      -
        name: Push Docker Image
        run: docker push -a macchina/device-agent

  docker-build-arm32v7:
    runs-on: ubuntu-20.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Available Platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Login to hub.docker.com
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build Docker Image
        run: |
          VERSION=`./version.sh`
          echo Version: ${VERSION}
          docker buildx build \
            --platform linux/arm/v7 \
            --output "type=image,push=true" \
            --tag macchina/device-agent:latest-arm32v7 \
            --tag macchina/device-agent:${VERSION}-arm32v7 \
            --file ./Dockerfile .

  docker-build-arm64v8:
    runs-on: ubuntu-20.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Available Platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Login to hub.docker.com
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build Docker Image
        run: |
          VERSION=`./version.sh`
          echo Version: ${VERSION}
          docker buildx build \
            --platform linux/arm64 \
            --output "type=image,push=true" \
            --tag macchina/device-agent:latest-arm64v8 \
            --tag macchina/device-agent:${VERSION}-arm64v8 \
            --file ./Dockerfile .

  docker-manifest:
    runs-on: ubuntu-20.04
    needs: ["docker-build-amd64", "docker-build-arm32v7", "docker-build-arm64v8"]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to hub.docker.com
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Create and Publish Manifest
        run: |
          VERSION=`./version.sh`
          echo Version: ${VERSION}
          docker manifest create \
            macchina/device-agent:latest \
            --amend macchina/device-agent:latest-amd64 \
            --amend macchina/device-agent:latest-arm32v7 \
            --amend macchina/device-agent:latest-arm64v8
          docker manifest create \
            macchina/device-agent:${VERSION} \
            --amend macchina/device-agent:${VERSION}-amd64 \
            --amend macchina/device-agent:${VERSION}-arm32v7 \
            --amend macchina/device-agent:${VERSION}-arm64v8
          docker manifest push macchina/device-agent:latest
          docker manifest push macchina/device-agent:${VERSION}
